-- 1. Updates to Profiles Table for SMS, Availability, and Zipcode tracking
ALTER TABLE profiles 
ADD COLUMN IF NOT EXISTS phone text,
ADD COLUMN IF NOT EXISTS sms_notifications boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS is_available boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS active_zipcode text;

-- 2. Professional Portfolios (Before & After Photos)
CREATE TABLE IF NOT EXISTS portfolios (
    id bigint generated by default as identity primary key,
    pro_id uuid references profiles(id) not null,
    before_image text,
    after_image text,
    description text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

ALTER TABLE portfolios ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public portfolios are viewable by everyone." ON portfolios FOR SELECT USING (true);
CREATE POLICY "Pros can manage their own portfolios." ON portfolios FOR ALL USING (auth.uid() = pro_id);


-- 3. Homeowner Completed Projects (Before & After Photos)
CREATE TABLE IF NOT EXISTS completed_projects (
    id bigint generated by default as identity primary key,
    homeowner_id uuid references profiles(id) not null,
    request_id bigint references service_requests(id),
    pro_id uuid references profiles(id),
    before_image text,
    after_image text,
    notes text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

ALTER TABLE completed_projects ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Completed projects are viewable by everyone." ON completed_projects FOR SELECT USING (true);
CREATE POLICY "Homeowners can manage their own projects." ON completed_projects FOR ALL USING (auth.uid() = homeowner_id);

-- Optional Note: In a production app, the `before_image` and `after_image` fields 
-- would ideally store Supabase Storage URLs rather than raw base64. Ensure you 
-- have a bucket called 'project-images' if you plan to migrate to proper file storage.
