-- 0. Cleanup (Run this to reset tables if they exist)
drop table if exists request_contact_info cascade;
drop table if exists bids cascade;

-- 1. Create Private Contact Info Table
create table request_contact_info (
  request_id bigint references service_requests(id) on delete cascade primary key,
  contact_name text,
  contact_email text,
  contact_phone text,
  exact_address text -- moving address here if needed, or keep generic city in public
);

-- Enable RLS
alter table request_contact_info enable row level security;

-- Policy 1: Homeowner (Creator) can view their own private info
create policy "Homeowner can view own private info"
on request_contact_info for select
using (
  exists (
    select 1 from service_requests
    where id = request_contact_info.request_id
    and user_id = auth.uid()
  )
);

-- Policy 2: Accepted Professional can view private info
-- (We will create the bids table next, this policy depends on it)
-- Placeholder for now, typically:
-- exists (select 1 from bids where request_id = ... and pro_id = auth.uid() and status = 'accepted')


-- 2. Create Bids Table
create table bids (
  id bigint generated by default as identity primary key,
  request_id bigint references service_requests(id) on delete cascade not null,
  pro_id uuid references auth.users not null,
  pro_name text, -- snapshot of pro name
  pro_avatar text, 
  price_estimate text,
  message text,
  status text default 'pending', -- pending, accepted, rejected
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table bids enable row level security;

-- Policy 3: Professionals can view/edit ONLY their own bids
create policy "Pros can view own bids"
on bids for select
using (pro_id = auth.uid());

create policy "Pros can insert bids"
on bids for insert
with check (pro_id = auth.uid());

-- Policy 4: Homeowners can view ALL bids for their requests
create policy "Homeowners can view bids on their requests"
on bids for select
using (
  exists (
    select 1 from service_requests
    where id = bids.request_id
    and user_id = auth.uid()
  )
);

-- Policy 5: Homeowners can update bid status (Accept/Reject)
create policy "Homeowners can update bid status"
on bids for update
using (
  exists (
    select 1 from service_requests
    where id = bids.request_id
    and user_id = auth.uid()
  )
);


-- 3. Update Policy for Private Info (Now that bids table exists)
create policy "Accepted Pro can view private info"
on request_contact_info for select
using (
  exists (
    select 1 from bids
    where request_id = request_contact_info.request_id
    and pro_id = auth.uid()
    and status = 'accepted'
  )
);


-- 4. Data Migration (Optional - Run if you want to move existing data)
-- insert into request_contact_info (request_id, contact_name, contact_email, contact_phone)
-- select id, contact_name, contact_email, contact_phone from service_requests;

-- 5. Cleanup (Optional - Run after migration verified)
-- alter table service_requests drop column contact_name;
-- alter table service_requests drop column contact_email;
-- alter table service_requests drop column contact_phone;
