
-- 1. Profiles Table (Extends Supabase Auth)
create table profiles (
  id uuid references auth.users not null primary key,
  email text,
  name text,
  type text, -- 'homeowner' or 'professional'
  role text default 'user', -- 'admin' or 'user'
  avatar text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone." on profiles for select using (true);
create policy "Users can insert their own profile." on profiles for insert with check (auth.uid() = id);
create policy "Users can update own profile." on profiles for update using (auth.uid() = id);

-- 2. Service Requests Table
create table service_requests (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  category text not null,
  details text,
  urgency text,
  city_state text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  status text default 'open', -- open, in_progress, completed
  
  -- Additional fields
  property_type text,
  home_age text,
  primary_residence text,
  service_goal text,
  service_time text,
  start_time text
);

alter table service_requests enable row level security;


-- Helper Function for RLS (Prevents Recursion)
create or replace function has_bid_on_request(request_id bigint)
returns boolean
language plpgsql
security definer -- <--- This allows checking Bids without triggering the infinite loop
as $$
begin
  return exists (
    select 1 from bids 
    where bids.request_id = request_id 
    and bids.pro_id = auth.uid()
  );
end;
$$;

-- Policies for Service Requests
create policy "Homeowners view own requests" on service_requests for select using (auth.uid() = user_id);
create policy "Users can create requests" on service_requests for insert with check (auth.uid() = user_id);
create policy "Users can update own requests" on service_requests for update using (auth.uid() = user_id);
create policy "Users can delete own requests" on service_requests for delete using (auth.uid() = user_id);

-- Pro Visibility Policies
create policy "Pros view requests they bid on"
on service_requests for select
using (
  status = 'open'         -- Can see all open jobs
  OR
  has_bid_on_request(id)  -- OR jobs I have bid on (using the safe function)
);


-- 3. Bids Table
create table bids (
  id bigint generated by default as identity primary key,
  request_id bigint references service_requests on delete cascade not null,
  pro_id uuid references profiles(id) not null,
  pro_name text,
  price_estimate text,
  message text,
  status text default 'pending', -- pending, accepted, rejected
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table bids enable row level security;

-- Policies for Bids
create policy "Pros_View_Own" on bids for select using (auth.uid() = pro_id);
create policy "Pros_Insert_Own" on bids for insert with check (auth.uid() = pro_id);

create policy "Homeowners_View_Request_Bids" on bids for select 
using (
  auth.uid() in (
    select user_id from service_requests where id = bids.request_id
  )
);

create policy "Homeowners_Update_Bids" on bids for update 
using (
  auth.uid() in (
    select user_id from service_requests where id = bids.request_id
  )
);

-- 4. Request Contact Info (Secure Table)
create table request_contact_info (
  id bigint generated by default as identity primary key,
  request_id bigint references service_requests on delete cascade not null,
  contact_name text,
  contact_email text,
  contact_phone text,
  exact_address text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table request_contact_info enable row level security;

-- Policies for Contact Info
create policy "Homeowners_Manage_Info" on request_contact_info 
using (
  auth.uid() in (
    select user_id from service_requests where id = request_contact_info.request_id
  )
);

create policy "Pros_View_Accepted_Info" on request_contact_info for select 
using (
  exists (
    select 1 from bids 
    where bids.request_id = request_contact_info.request_id 
    and bids.pro_id = auth.uid() 
    and bids.status = 'accepted'
  )
);

-- 5. Forum Tables (Existing)
create table forum_questions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  name text,
  email text,
  category text,
  question text not null,
  upvotes int default 0,
  media_url text,
  media_type text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table forum_questions enable row level security;

create policy "Everyone can view questions." on forum_questions for select using (true);
create policy "Authenticated users can create questions." on forum_questions for insert with check (auth.role() = 'authenticated');
create policy "Users can update own questions." on forum_questions for update using (auth.uid() = user_id);
create policy "Users can delete own questions." on forum_questions for delete using (auth.uid() = user_id);

create table forum_replies (
  id bigint generated by default as identity primary key,
  question_id bigint references forum_questions on delete cascade not null,
  user_id uuid references auth.users not null,
  user_name text,
  text text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table forum_replies enable row level security;

create policy "Everyone can view replies." on forum_replies for select using (true);
create policy "Authenticated users can reply." on forum_replies for insert with check (auth.role() = 'authenticated');
